# Generated by Django 3.2.6 on 2023-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contrasena',
            field=models.TextField(default='', max_length=100),
        ),
    ]
