# Generated by Django 3.2.6 on 2023-10-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_customuser_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_administrador',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_medico',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_paciente',
            new_name='is_patient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contrasena',
        ),
    ]
